name: product_manager
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  card_swiper: ^3.0.1
  dio: ^5.4.2+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.0
  go_router: ^13.2.2
  intl: ^0.18.1
  mocktail: ^1.0.3
  riverpod_annotation: ^2.3.5
  shimmer: ^3.0.0

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
